; Slugname lavandula
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Lavandula
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #050014
DARK_BLACK = 5,0,20

; ANSI Black Bright
; 1;30m
; base03 #463c53
BRIGHT_BLACK = 70,60,83

; ANSI Red
; 31m / 41m
; base08 #7c1525
DARK_RED = 124,21,37

; ANSI Red Bright
; 1;31m
; base12 #df5066
BRIGHT_RED = 223,80,102

; ANSI Green
; 32m / 42m
; base0B #337e6f
DARK_GREEN = 51,126,111

; ANSI Green Bright
; 1;32m
; base14 #52e0c4
BRIGHT_GREEN = 82,224,196

; ANSI Yellow
; 33m / 43m
; base0A #8e86df
DARK_YELLOW = 142,134,223

; ANSI Yellow Bright
; 1;33m
; base13 #e0c286
BRIGHT_YELLOW = 224,194,134

; ANSI Blue
; 34m / 44m
; base0D #4f4a7f
DARK_BLUE = 79,74,127

; ANSI Blue Bright
; 1;34m
; base16 #8e86df
BRIGHT_BLUE = 142,134,223

; ANSI Magenta
; 35m / 45m
; base0E #593f7e
DARK_MAGENTA = 89,63,126

; ANSI Magenta Bright
; 1;35m
; base17 #a675df
BRIGHT_MAGENTA = 166,117,223

; ANSI Cyan
; 36m / 46m
; base0C #57767f
DARK_CYAN = 87,118,127

; ANSI Cyan Bright
; 1;36m
; base15 #9ad3df
BRIGHT_CYAN = 154,211,223

; ANSI White
; 37m / 47m
; base06 #736e7d
DARK_WHITE = 115,110,125

; ANSI White Bright
; 1;37m
; base07 #8c91fa
BRIGHT_WHITE = 140,145,250

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #645d6f
FOREGROUND = 100,93,111
; background #050014
BACKGROUND = 5,0,20


; generated from https://github.com/clach04/base24_colortool
