; Slugname ubuntu
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Ubuntu
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #300a24
DARK_BLACK = 48,10,36

; ANSI Black Bright
; 1;30m
; base03 #747772
BRIGHT_BLACK = 116,119,114

; ANSI Red
; 31m / 41m
; base08 #cc0000
DARK_RED = 204,0,0

; ANSI Red Bright
; 1;31m
; base12 #ef2929
BRIGHT_RED = 239,41,41

; ANSI Green
; 32m / 42m
; base0B #4e9a06
DARK_GREEN = 78,154,6

; ANSI Green Bright
; 1;32m
; base14 #8ae234
BRIGHT_GREEN = 138,226,52

; ANSI Yellow
; 33m / 43m
; base0A #729fcf
DARK_YELLOW = 114,159,207

; ANSI Yellow Bright
; 1;33m
; base13 #fce94f
BRIGHT_YELLOW = 252,233,79

; ANSI Blue
; 34m / 44m
; base0D #3465a4
DARK_BLUE = 52,101,164

; ANSI Blue Bright
; 1;34m
; base16 #729fcf
BRIGHT_BLUE = 114,159,207

; ANSI Magenta
; 35m / 45m
; base0E #75507b
DARK_MAGENTA = 117,80,123

; ANSI Magenta Bright
; 1;35m
; base17 #ad7fa8
BRIGHT_MAGENTA = 173,127,168

; ANSI Cyan
; 36m / 46m
; base0C #06989a
DARK_CYAN = 6,152,154

; ANSI Cyan Bright
; 1;36m
; base15 #34e2e2
BRIGHT_CYAN = 52,226,226

; ANSI White
; 37m / 47m
; base06 #d3d7cf
DARK_WHITE = 211,215,207

; ANSI White Bright
; 1;37m
; base07 #eeeeec
BRIGHT_WHITE = 238,238,236

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #b3b7b0
FOREGROUND = 179,183,176
; background #300a24
BACKGROUND = 48,10,36


; generated from https://github.com/clach04/base24_colortool
