; Slugname toy-chest
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Toy Chest
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #23364a
DARK_BLACK = 35,54,74

; ANSI Black Bright
; 1;30m
; base03 #2f8288
BRIGHT_BLACK = 47,130,136

; ANSI Red
; 31m / 41m
; base08 #be2d26
DARK_RED = 190,45,38

; ANSI Red Bright
; 1;31m
; base12 #dd5943
BRIGHT_RED = 221,89,67

; ANSI Green
; 32m / 42m
; base0B #199171
DARK_GREEN = 25,145,113

; ANSI Green Bright
; 1;32m
; base14 #30cf7b
BRIGHT_GREEN = 48,207,123

; ANSI Yellow
; 33m / 43m
; base0A #33a5d9
DARK_YELLOW = 51,165,217

; ANSI Yellow Bright
; 1;33m
; base13 #e7d74b
BRIGHT_YELLOW = 231,215,75

; ANSI Blue
; 34m / 44m
; base0D #325d96
DARK_BLUE = 50,93,150

; ANSI Blue Bright
; 1;34m
; base16 #33a5d9
BRIGHT_BLUE = 51,165,217

; ANSI Magenta
; 35m / 45m
; base0E #8a5ddb
DARK_MAGENTA = 138,93,219

; ANSI Magenta Bright
; 1;35m
; base17 #ad6bdc
BRIGHT_MAGENTA = 173,107,220

; ANSI Cyan
; 36m / 46m
; base0C #35a08f
DARK_CYAN = 53,160,143

; ANSI Cyan Bright
; 1;36m
; base15 #41c3ad
BRIGHT_CYAN = 65,195,173

; ANSI White
; 37m / 47m
; base06 #23d082
DARK_WHITE = 35,208,130

; ANSI White Bright
; 1;37m
; base07 #d4d4d4
BRIGHT_WHITE = 212,212,212

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #27b684
FOREGROUND = 39,182,132
; background #23364a
BACKGROUND = 35,54,74


; generated from https://github.com/clach04/base24_colortool
