; Slugname tokyo-night-light
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Tokyo Night Light
author  =  Michaël Ball, based on Tokyo Night by enkia (https://github.com/enkia/tokyo-night-vscode-theme)

[table]

; ANSI Black
; 30m / 40m
; base00 #d5d6db
DARK_BLACK = 213,214,219

; ANSI Black Bright
; 1;30m
; base03 #9699a3
BRIGHT_BLACK = 150,153,163

; ANSI Red
; 31m / 41m
; base08 #343b59
DARK_RED = 52,59,89

; ANSI Red Bright
; 1;31m
; base12 #8c4351
BRIGHT_RED = 140,67,81

; ANSI Green
; 32m / 42m
; base0B #485e30
DARK_GREEN = 72,94,48

; ANSI Green Bright
; 1;32m
; base14 #485e30
BRIGHT_GREEN = 72,94,48

; ANSI Yellow
; 33m / 43m
; base0A #166775
DARK_YELLOW = 22,103,117

; ANSI Yellow Bright
; 1;33m
; base13 #965027
BRIGHT_YELLOW = 150,80,39

; ANSI Blue
; 34m / 44m
; base0D #34548a
DARK_BLUE = 52,84,138

; ANSI Blue Bright
; 1;34m
; base16 #34548a
BRIGHT_BLUE = 52,84,138

; ANSI Magenta
; 35m / 45m
; base0E #5a4a78
DARK_MAGENTA = 90,74,120

; ANSI Magenta Bright
; 1;35m
; base17 #5a4a78
BRIGHT_MAGENTA = 90,74,120

; ANSI Cyan
; 36m / 46m
; base0C #3e6968
DARK_CYAN = 62,105,104

; ANSI Cyan Bright
; 1;36m
; base15 #3e6968
BRIGHT_CYAN = 62,105,104

; ANSI White
; 37m / 47m
; base06 #1a1b26
DARK_WHITE = 26,27,38

; ANSI White Bright
; 1;37m
; base07 #1a1b26
BRIGHT_WHITE = 26,27,38

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #343b59
FOREGROUND = 52,59,89
; background #d5d6db
BACKGROUND = 213,214,219


; generated from https://github.com/clach04/base24_colortool
