; Slugname builtin-solarized-light
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Builtin Solarized Light
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #fdf6e3
DARK_BLACK = 253,246,227

; ANSI Black Bright
; 1;30m
; base03 #3b5a5d
BRIGHT_BLACK = 59,90,93

; ANSI Red
; 31m / 41m
; base08 #dc322f
DARK_RED = 220,50,47

; ANSI Red Bright
; 1;31m
; base12 #cb4b16
BRIGHT_RED = 203,75,22

; ANSI Green
; 32m / 42m
; base0B #859900
DARK_GREEN = 133,153,0

; ANSI Green Bright
; 1;32m
; base14 #586e75
BRIGHT_GREEN = 88,110,117

; ANSI Yellow
; 33m / 43m
; base0A #839496
DARK_YELLOW = 131,148,150

; ANSI Yellow Bright
; 1;33m
; base13 #657b83
BRIGHT_YELLOW = 101,123,131

; ANSI Blue
; 34m / 44m
; base0D #268bd2
DARK_BLUE = 38,139,210

; ANSI Blue Bright
; 1;34m
; base16 #839496
BRIGHT_BLUE = 131,148,150

; ANSI Magenta
; 35m / 45m
; base0E #d33682
DARK_MAGENTA = 211,54,130

; ANSI Magenta Bright
; 1;35m
; base17 #6c71c4
BRIGHT_MAGENTA = 108,113,196

; ANSI Cyan
; 36m / 46m
; base0C #2aa198
DARK_CYAN = 42,161,152

; ANSI Cyan Bright
; 1;36m
; base15 #93a1a1
BRIGHT_CYAN = 147,161,161

; ANSI White
; 37m / 47m
; base06 #eee8d5
DARK_WHITE = 238,232,213

; ANSI White Bright
; 1;37m
; base07 #fdf6e3
BRIGHT_WHITE = 253,246,227

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #b2b8ad
FOREGROUND = 178,184,173
; background #fdf6e3
BACKGROUND = 253,246,227


; generated from https://github.com/clach04/base24_colortool
