; Slugname later-this-evening
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Later This Evening
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #212121
DARK_BLACK = 33,33,33

; ANSI Black Bright
; 1;30m
; base03 #6f6f6f
BRIGHT_BLACK = 111,111,111

; ANSI Red
; 31m / 41m
; base08 #d35a5f
DARK_RED = 211,90,95

; ANSI Red Bright
; 1;31m
; base12 #d3222e
BRIGHT_RED = 211,34,46

; ANSI Green
; 32m / 42m
; base0B #afba66
DARK_GREEN = 175,186,102

; ANSI Green Bright
; 1;32m
; base14 #aabb39
BRIGHT_GREEN = 170,187,57

; ANSI Yellow
; 33m / 43m
; base0A #e5d289
DARK_YELLOW = 229,210,137

; ANSI Yellow Bright
; 1;33m
; base13 #e4bd39
BRIGHT_YELLOW = 228,189,57

; ANSI Blue
; 34m / 44m
; base0D #a0b9d5
DARK_BLUE = 160,185,213

; ANSI Blue Bright
; 1;34m
; base16 #6599d5
BRIGHT_BLUE = 101,153,213

; ANSI Magenta
; 35m / 45m
; base0E #bf92d5
DARK_MAGENTA = 191,146,213

; ANSI Magenta Bright
; 1;35m
; base17 #aa52d5
BRIGHT_MAGENTA = 170,82,213

; ANSI Cyan
; 36m / 46m
; base0C #91beb6
DARK_CYAN = 145,190,182

; ANSI Cyan Bright
; 1;36m
; base15 #5fbfad
BRIGHT_CYAN = 95,191,173

; ANSI White
; 37m / 47m
; base06 #bfbfbf
DARK_WHITE = 191,191,191

; ANSI White Bright
; 1;37m
; base07 #d9d9d9
BRIGHT_WHITE = 217,217,217

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #a6a6a6
FOREGROUND = 166,166,166
; background #212121
BACKGROUND = 33,33,33


; generated from https://github.com/clach04/base24_colortool
