; Slugname dimmed-monokai
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Dimmed Monokai
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #1e1e1e
DARK_BLACK = 30,30,30

; ANSI Black Bright
; 1;30m
; base03 #949593
BRIGHT_BLACK = 148,149,147

; ANSI Red
; 31m / 41m
; base08 #be3e48
DARK_RED = 190,62,72

; ANSI Red Bright
; 1;31m
; base12 #fb001e
BRIGHT_RED = 251,0,30

; ANSI Green
; 32m / 42m
; base0B #869a3a
DARK_GREEN = 134,154,58

; ANSI Green Bright
; 1;32m
; base14 #0e712e
BRIGHT_GREEN = 14,113,46

; ANSI Yellow
; 33m / 43m
; base0A #176ce3
DARK_YELLOW = 23,108,227

; ANSI Yellow Bright
; 1;33m
; base13 #c37033
BRIGHT_YELLOW = 195,112,51

; ANSI Blue
; 34m / 44m
; base0D #4e76a1
DARK_BLUE = 78,118,161

; ANSI Blue Bright
; 1;34m
; base16 #176ce3
BRIGHT_BLUE = 23,108,227

; ANSI Magenta
; 35m / 45m
; base0E #855b8d
DARK_MAGENTA = 133,91,141

; ANSI Magenta Bright
; 1;35m
; base17 #fb0067
BRIGHT_MAGENTA = 251,0,103

; ANSI Cyan
; 36m / 46m
; base0C #568ea3
DARK_CYAN = 86,142,163

; ANSI Cyan Bright
; 1;36m
; base15 #2d6f6c
BRIGHT_CYAN = 45,111,108

; ANSI White
; 37m / 47m
; base06 #b8bcb9
DARK_WHITE = 184,188,185

; ANSI White Bright
; 1;37m
; base07 #fcffb8
BRIGHT_WHITE = 252,255,184

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #acafac
FOREGROUND = 172,175,172
; background #1e1e1e
BACKGROUND = 30,30,30


; generated from https://github.com/clach04/base24_colortool
