; Slugname ollie
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Ollie
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #212024
DARK_BLACK = 33,32,36

; ANSI Black Bright
; 1;30m
; base03 #664b46
BRIGHT_BLACK = 102,75,70

; ANSI Red
; 31m / 41m
; base08 #ab2e30
DARK_RED = 171,46,48

; ANSI Red Bright
; 1;31m
; base12 #ff3d48
BRIGHT_RED = 255,61,72

; ANSI Green
; 32m / 42m
; base0B #31ab60
DARK_GREEN = 49,171,96

; ANSI Green Bright
; 1;32m
; base14 #3bff99
BRIGHT_GREEN = 59,255,153

; ANSI Yellow
; 33m / 43m
; base0A #4487ff
DARK_YELLOW = 68,135,255

; ANSI Yellow Bright
; 1;33m
; base13 #ff5e1e
BRIGHT_YELLOW = 255,94,30

; ANSI Blue
; 34m / 44m
; base0D #2c56ab
DARK_BLUE = 44,86,171

; ANSI Blue Bright
; 1;34m
; base16 #4487ff
BRIGHT_BLUE = 68,135,255

; ANSI Magenta
; 35m / 45m
; base0E #af8427
DARK_MAGENTA = 175,132,39

; ANSI Magenta Bright
; 1;35m
; base17 #ffc21c
BRIGHT_MAGENTA = 255,194,28

; ANSI Cyan
; 36m / 46m
; base0C #1fa5ab
DARK_CYAN = 31,165,171

; ANSI Cyan Bright
; 1;36m
; base15 #1efaff
BRIGHT_CYAN = 30,250,255

; ANSI White
; 37m / 47m
; base06 #8a8dab
DARK_WHITE = 138,141,171

; ANSI White Bright
; 1;37m
; base07 #5b6da7
BRIGHT_WHITE = 91,109,167

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #7e7789
FOREGROUND = 126,119,137
; background #212024
BACKGROUND = 33,32,36


; generated from https://github.com/clach04/base24_colortool
