; Slugname ciapre
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Ciapre
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #181c27
DARK_BLACK = 24,28,39

; ANSI Black Bright
; 1;30m
; base03 #6b685f
BRIGHT_BLACK = 107,104,95

; ANSI Red
; 31m / 41m
; base08 #800009
DARK_RED = 128,0,9

; ANSI Red Bright
; 1;31m
; base12 #ab3834
BRIGHT_RED = 171,56,52

; ANSI Green
; 32m / 42m
; base0B #48513b
DARK_GREEN = 72,81,59

; ANSI Green Bright
; 1;32m
; base14 #a6a65d
BRIGHT_GREEN = 166,166,93

; ANSI Yellow
; 33m / 43m
; base0A #2f97c6
DARK_YELLOW = 47,151,198

; ANSI Yellow Bright
; 1;33m
; base13 #dcde7b
BRIGHT_YELLOW = 220,222,123

; ANSI Blue
; 34m / 44m
; base0D #566d8c
DARK_BLUE = 86,109,140

; ANSI Blue Bright
; 1;34m
; base16 #2f97c6
BRIGHT_BLUE = 47,151,198

; ANSI Magenta
; 35m / 45m
; base0E #724c7c
DARK_MAGENTA = 114,76,124

; ANSI Magenta Bright
; 1;35m
; base17 #d33060
BRIGHT_MAGENTA = 211,48,96

; ANSI Cyan
; 36m / 46m
; base0C #5b4f4a
DARK_CYAN = 91,79,74

; ANSI Cyan Bright
; 1;36m
; base15 #f3dab1
BRIGHT_CYAN = 243,218,177

; ANSI White
; 37m / 47m
; base06 #ada37e
DARK_WHITE = 173,163,126

; ANSI White Bright
; 1;37m
; base07 #f3f3f3
BRIGHT_WHITE = 243,243,243

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #978f73
FOREGROUND = 151,143,115
; background #181c27
BACKGROUND = 24,28,39


; generated from https://github.com/clach04/base24_colortool
