; Slugname sparky
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Sparky
author  =  Leila Sother (https://github.com/mixcoac)

[table]

; ANSI Black
; 30m / 40m
; base00 #072b31
DARK_BLACK = 7,43,49

; ANSI Black Bright
; 1;30m
; base03 #003b49
BRIGHT_BLACK = 0,59,73

; ANSI Red
; 31m / 41m
; base08 #ff585d
DARK_RED = 255,88,93

; ANSI Red Bright
; 1;31m
; base12 #ff7276
BRIGHT_RED = 255,114,118

; ANSI Green
; 32m / 42m
; base0B #78d64b
DARK_GREEN = 120,214,75

; ANSI Green Bright
; 1;32m
; base14 #8edd65
BRIGHT_GREEN = 142,221,101

; ANSI Yellow
; 33m / 43m
; base0A #fbdd40
DARK_YELLOW = 251,221,64

; ANSI Yellow Bright
; 1;33m
; base13 #f6eb61
BRIGHT_YELLOW = 246,235,97

; ANSI Blue
; 34m / 44m
; base0D #4698cb
DARK_BLUE = 70,152,203

; ANSI Blue Bright
; 1;34m
; base16 #69b3e7
BRIGHT_BLUE = 105,179,231

; ANSI Magenta
; 35m / 45m
; base0E #d59ed7
DARK_MAGENTA = 213,158,215

; ANSI Magenta Bright
; 1;35m
; base17 #f99fc9
BRIGHT_MAGENTA = 249,159,201

; ANSI Cyan
; 36m / 46m
; base0C #2dccd3
DARK_CYAN = 45,204,211

; ANSI Cyan Bright
; 1;36m
; base15 #00c1d5
BRIGHT_CYAN = 0,193,213

; ANSI White
; 37m / 47m
; base06 #f5f5f1
DARK_WHITE = 245,245,241

; ANSI White Bright
; 1;37m
; base07 #ffffff
BRIGHT_WHITE = 255,255,255

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #f4f5f0
FOREGROUND = 244,245,240
; background #072b31
BACKGROUND = 7,43,49


; generated from https://github.com/clach04/base24_colortool
