; Slugname unikitty
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Unikitty
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #ff7ad3
DARK_BLACK = 255,122,211

; ANSI Black Bright
; 1;30m
; base03 #696769
BRIGHT_BLACK = 105,103,105

; ANSI Red
; 31m / 41m
; base08 #a80f20
DARK_RED = 168,15,32

; ANSI Red Bright
; 1;31m
; base12 #d81329
BRIGHT_RED = 216,19,41

; ANSI Green
; 32m / 42m
; base0B #bafc8b
DARK_GREEN = 186,252,139

; ANSI Green Bright
; 1;32m
; base14 #d2ffaf
BRIGHT_GREEN = 210,255,175

; ANSI Yellow
; 33m / 43m
; base0A #eedf4b
DARK_YELLOW = 238,223,75

; ANSI Yellow Bright
; 1;33m
; base13 #ffee50
BRIGHT_YELLOW = 255,238,80

; ANSI Blue
; 34m / 44m
; base0D #145fcd
DARK_BLUE = 20,95,205

; ANSI Blue Bright
; 1;34m
; base16 #0074ea
BRIGHT_BLUE = 0,116,234

; ANSI Magenta
; 35m / 45m
; base0E #ff36a2
DARK_MAGENTA = 255,54,162

; ANSI Magenta Bright
; 1;35m
; base17 #fdd5e5
BRIGHT_MAGENTA = 253,213,229

; ANSI Cyan
; 36m / 46m
; base0C #6bd0bc
DARK_CYAN = 107,208,188

; ANSI Cyan Bright
; 1;36m
; base15 #79ebd5
BRIGHT_CYAN = 121,235,213

; ANSI White
; 37m / 47m
; base06 #e1d6e0
DARK_WHITE = 225,214,224

; ANSI White Bright
; 1;37m
; base07 #fff2fd
BRIGHT_WHITE = 255,242,253

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #b9b1b8
FOREGROUND = 185,177,184
; background #ff7ad3
BACKGROUND = 255,122,211


; generated from https://github.com/clach04/base24_colortool
