; Slugname slate
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Slate
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #212121
DARK_BLACK = 33,33,33

; ANSI Black Bright
; 1;30m
; base03 #c0f1f8
BRIGHT_BLACK = 192,241,248

; ANSI Red
; 31m / 41m
; base08 #e1a7bf
DARK_RED = 225,167,191

; ANSI Red Bright
; 1;31m
; base12 #ffccd8
BRIGHT_RED = 255,204,216

; ANSI Green
; 32m / 42m
; base0B #80d778
DARK_GREEN = 128,215,120

; ANSI Green Bright
; 1;32m
; base14 #bdffa8
BRIGHT_GREEN = 189,255,168

; ANSI Yellow
; 33m / 43m
; base0A #79afd2
DARK_YELLOW = 121,175,210

; ANSI Yellow Bright
; 1;33m
; base13 #d0cbc9
BRIGHT_YELLOW = 208,203,201

; ANSI Blue
; 34m / 44m
; base0D #254a49
DARK_BLUE = 37,74,73

; ANSI Blue Bright
; 1;34m
; base16 #79afd2
BRIGHT_BLUE = 121,175,210

; ANSI Magenta
; 35m / 45m
; base0E #a380d3
DARK_MAGENTA = 163,128,211

; ANSI Magenta Bright
; 1;35m
; base17 #c4a7d8
BRIGHT_MAGENTA = 196,167,216

; ANSI Cyan
; 36m / 46m
; base0C #14ab9c
DARK_CYAN = 20,171,156

; ANSI Cyan Bright
; 1;36m
; base15 #8bdee0
BRIGHT_CYAN = 139,222,224

; ANSI White
; 37m / 47m
; base06 #02c4e0
DARK_WHITE = 2,196,224

; ANSI White Bright
; 1;37m
; base07 #e0e0e0
BRIGHT_WHITE = 224,224,224

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #42d3e8
FOREGROUND = 66,211,232
; background #212121
BACKGROUND = 33,33,33


; generated from https://github.com/clach04/base24_colortool
