; Slugname github-light
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Github Light
author  =  Tinted Theming (https://github.com/tinted-theming)

[table]

; ANSI Black
; 30m / 40m
; base00 #eaeef2
DARK_BLACK = 234,238,242

; ANSI Black Bright
; 1;30m
; base03 #8c959f
BRIGHT_BLACK = 140,149,159

; ANSI Red
; 31m / 41m
; base08 #fa4549
DARK_RED = 250,69,73

; ANSI Red Bright
; 1;31m
; base12 #ff8182
BRIGHT_RED = 255,129,130

; ANSI Green
; 32m / 42m
; base0B #2da44e
DARK_GREEN = 45,164,78

; ANSI Green Bright
; 1;32m
; base14 #4ac26b
BRIGHT_GREEN = 74,194,107

; ANSI Yellow
; 33m / 43m
; base0A #bf8700
DARK_YELLOW = 191,135,0

; ANSI Yellow Bright
; 1;33m
; base13 #d4a72c
BRIGHT_YELLOW = 212,167,44

; ANSI Blue
; 34m / 44m
; base0D #218bff
DARK_BLUE = 33,139,255

; ANSI Blue Bright
; 1;34m
; base16 #54aeff
BRIGHT_BLUE = 84,174,255

; ANSI Magenta
; 35m / 45m
; base0E #a475f9
DARK_MAGENTA = 164,117,249

; ANSI Magenta Bright
; 1;35m
; base17 #c297ff
BRIGHT_MAGENTA = 194,151,255

; ANSI Cyan
; 36m / 46m
; base0C #339d9b
DARK_CYAN = 51,157,155

; ANSI Cyan Bright
; 1;36m
; base15 #49bcb7
BRIGHT_CYAN = 73,188,183

; ANSI White
; 37m / 47m
; base06 #32383f
DARK_WHITE = 50,56,63

; ANSI White Bright
; 1;37m
; base07 #1f2328
BRIGHT_WHITE = 31,35,40

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #424a53
FOREGROUND = 66,74,83
; background #eaeef2
BACKGROUND = 234,238,242


; generated from https://github.com/clach04/base24_colortool
