; Slugname shades-of-purple
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Shades Of Purple
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #1e1d40
DARK_BLACK = 30,29,64

; ANSI Black Bright
; 1;30m
; base03 #7f7f7f
BRIGHT_BLACK = 127,127,127

; ANSI Red
; 31m / 41m
; base08 #d90429
DARK_RED = 217,4,41

; ANSI Red Bright
; 1;31m
; base12 #f9291b
BRIGHT_RED = 249,41,27

; ANSI Green
; 32m / 42m
; base0B #3ad900
DARK_GREEN = 58,217,0

; ANSI Green Bright
; 1;32m
; base14 #42d425
BRIGHT_GREEN = 66,212,37

; ANSI Yellow
; 33m / 43m
; base0A #6871ff
DARK_YELLOW = 104,113,255

; ANSI Yellow Bright
; 1;33m
; base13 #f1d000
BRIGHT_YELLOW = 241,208,0

; ANSI Blue
; 34m / 44m
; base0D #6943ff
DARK_BLUE = 105,67,255

; ANSI Blue Bright
; 1;34m
; base16 #6871ff
BRIGHT_BLUE = 104,113,255

; ANSI Magenta
; 35m / 45m
; base0E #ff2b70
DARK_MAGENTA = 255,43,112

; ANSI Magenta Bright
; 1;35m
; base17 #ff76ff
BRIGHT_MAGENTA = 255,118,255

; ANSI Cyan
; 36m / 46m
; base0C #00c5c7
DARK_CYAN = 0,197,199

; ANSI Cyan Bright
; 1;36m
; base15 #79e7fa
BRIGHT_CYAN = 121,231,250

; ANSI White
; 37m / 47m
; base06 #c7c7c7
DARK_WHITE = 199,199,199

; ANSI White Bright
; 1;37m
; base07 #feffff
BRIGHT_WHITE = 254,255,255

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #afafaf
FOREGROUND = 175,175,175
; background #1e1d40
BACKGROUND = 30,29,64


; generated from https://github.com/clach04/base24_colortool
