; Slugname catppuccin-macchiato
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Catppuccin Macchiato
author  =  https://github.com/catppuccin/catppuccin

[table]

; ANSI Black
; 30m / 40m
; base00 #24273a
DARK_BLACK = 36,39,58

; ANSI Black Bright
; 1;30m
; base03 #494d64
BRIGHT_BLACK = 73,77,100

; ANSI Red
; 31m / 41m
; base08 #ed8796
DARK_RED = 237,135,150

; ANSI Red Bright
; 1;31m
; base12 #ee99a0
BRIGHT_RED = 238,153,160

; ANSI Green
; 32m / 42m
; base0B #a6da95
DARK_GREEN = 166,218,149

; ANSI Green Bright
; 1;32m
; base14 #a6da95
BRIGHT_GREEN = 166,218,149

; ANSI Yellow
; 33m / 43m
; base0A #eed49f
DARK_YELLOW = 238,212,159

; ANSI Yellow Bright
; 1;33m
; base13 #f4dbd6
BRIGHT_YELLOW = 244,219,214

; ANSI Blue
; 34m / 44m
; base0D #8aadf4
DARK_BLUE = 138,173,244

; ANSI Blue Bright
; 1;34m
; base16 #7dc4e4
BRIGHT_BLUE = 125,196,228

; ANSI Magenta
; 35m / 45m
; base0E #c6a0f6
DARK_MAGENTA = 198,160,246

; ANSI Magenta Bright
; 1;35m
; base17 #f5bde6
BRIGHT_MAGENTA = 245,189,230

; ANSI Cyan
; 36m / 46m
; base0C #8bd5ca
DARK_CYAN = 139,213,202

; ANSI Cyan Bright
; 1;36m
; base15 #91d7e3
BRIGHT_CYAN = 145,215,227

; ANSI White
; 37m / 47m
; base06 #f4dbd6
DARK_WHITE = 244,219,214

; ANSI White Bright
; 1;37m
; base07 #b7bdf8
BRIGHT_WHITE = 183,189,248

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #cad3f5
FOREGROUND = 202,211,245
; background #24273a
BACKGROUND = 36,39,58


; generated from https://github.com/clach04/base24_colortool
