; Slugname batman
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Batman
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #1b1d1e
DARK_BLACK = 27,29,30

; ANSI Black Bright
; 1;30m
; base03 #6d6f6e
BRIGHT_BLACK = 109,111,110

; ANSI Red
; 31m / 41m
; base08 #e6db43
DARK_RED = 230,219,67

; ANSI Red Bright
; 1;31m
; base12 #fff68d
BRIGHT_RED = 255,246,141

; ANSI Green
; 32m / 42m
; base0B #c8be46
DARK_GREEN = 200,190,70

; ANSI Green Bright
; 1;32m
; base14 #fff27c
BRIGHT_GREEN = 255,242,124

; ANSI Yellow
; 33m / 43m
; base0A #909495
DARK_YELLOW = 144,148,149

; ANSI Yellow Bright
; 1;33m
; base13 #feed6c
BRIGHT_YELLOW = 254,237,108

; ANSI Blue
; 34m / 44m
; base0D #737074
DARK_BLUE = 115,112,116

; ANSI Blue Bright
; 1;34m
; base16 #909495
BRIGHT_BLUE = 144,148,149

; ANSI Magenta
; 35m / 45m
; base0E #737271
DARK_MAGENTA = 115,114,113

; ANSI Magenta Bright
; 1;35m
; base17 #9a999d
BRIGHT_MAGENTA = 154,153,157

; ANSI Cyan
; 36m / 46m
; base0C #615f5e
DARK_CYAN = 97,95,94

; ANSI Cyan Bright
; 1;36m
; base15 #a2a2a5
BRIGHT_CYAN = 162,162,165

; ANSI White
; 37m / 47m
; base06 #c5c5be
DARK_WHITE = 197,197,190

; ANSI White Bright
; 1;37m
; base07 #dadad5
BRIGHT_WHITE = 218,218,213

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #a7a8a3
FOREGROUND = 167,168,163
; background #1b1d1e
BACKGROUND = 27,29,30


; generated from https://github.com/clach04/base24_colortool
