; Slugname kanagawa-dragon
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Kanagawa Dragon
author  =  Stefan Weigl-Bosker (https://github.com/sweiglbosker), Tommaso Laurenzi (https://github.com/rebelot/kanagawa.nvim)

[table]

; ANSI Black
; 30m / 40m
; base00 #181616
DARK_BLACK = 24,22,22

; ANSI Black Bright
; 1;30m
; base03 #625e5a
BRIGHT_BLACK = 98,94,90

; ANSI Red
; 31m / 41m
; base08 #c4746e
DARK_RED = 196,116,110

; ANSI Red Bright
; 1;31m
; base12 #e46876
BRIGHT_RED = 228,104,118

; ANSI Green
; 32m / 42m
; base0B #8a9a7b
DARK_GREEN = 138,154,123

; ANSI Green Bright
; 1;32m
; base14 #87a987
BRIGHT_GREEN = 135,169,135

; ANSI Yellow
; 33m / 43m
; base0A #c4b28a
DARK_YELLOW = 196,178,138

; ANSI Yellow Bright
; 1;33m
; base13 #e6c384
BRIGHT_YELLOW = 230,195,132

; ANSI Blue
; 34m / 44m
; base0D #8ba4b0
DARK_BLUE = 139,164,176

; ANSI Blue Bright
; 1;34m
; base16 #7fb4ca
BRIGHT_BLUE = 127,180,202

; ANSI Magenta
; 35m / 45m
; base0E #a292a3
DARK_MAGENTA = 162,146,163

; ANSI Magenta Bright
; 1;35m
; base17 #938aa9
BRIGHT_MAGENTA = 147,138,169

; ANSI Cyan
; 36m / 46m
; base0C #8ea4a2
DARK_CYAN = 142,164,162

; ANSI Cyan Bright
; 1;36m
; base15 #7aa89f
BRIGHT_CYAN = 122,168,159

; ANSI White
; 37m / 47m
; base06 #c8c093
DARK_WHITE = 200,192,147

; ANSI White Bright
; 1;37m
; base07 #c5c9c5
BRIGHT_WHITE = 197,201,197

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #c5c9c5
FOREGROUND = 197,201,197
; background #181616
BACKGROUND = 24,22,22


; generated from https://github.com/clach04/base24_colortool
