; Slugname purplepeter
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Purplepeter
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #2a1a4a
DARK_BLACK = 42,26,74

; ANSI Black Bright
; 1;30m
; base03 #4b3639
BRIGHT_BLACK = 75,54,57

; ANSI Red
; 31m / 41m
; base08 #ff786c
DARK_RED = 255,120,108

; ANSI Red Bright
; 1;31m
; base12 #f89f92
BRIGHT_RED = 248,159,146

; ANSI Green
; 32m / 42m
; base0B #98b481
DARK_GREEN = 152,180,129

; ANSI Green Bright
; 1;32m
; base14 #b4bd8e
BRIGHT_GREEN = 180,189,142

; ANSI Yellow
; 33m / 43m
; base0A #79daed
DARK_YELLOW = 121,218,237

; ANSI Yellow Bright
; 1;33m
; base13 #f1e9bf
BRIGHT_YELLOW = 241,233,191

; ANSI Blue
; 34m / 44m
; base0D #66d9ef
DARK_BLUE = 102,217,239

; ANSI Blue Bright
; 1;34m
; base16 #79daed
BRIGHT_BLUE = 121,218,237

; ANSI Magenta
; 35m / 45m
; base0E #e68ecd
DARK_MAGENTA = 230,142,205

; ANSI Magenta Bright
; 1;35m
; base17 #b991d4
BRIGHT_MAGENTA = 185,145,212

; ANSI Cyan
; 36m / 46m
; base0C #b98cff
DARK_CYAN = 185,140,255

; ANSI Cyan Bright
; 1;36m
; base15 #a0a0d6
BRIGHT_CYAN = 160,160,214

; ANSI White
; 37m / 47m
; base06 #ffba81
DARK_WHITE = 255,186,129

; ANSI White Bright
; 1;37m
; base07 #b9aed3
BRIGHT_WHITE = 185,174,211

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #c38e69
FOREGROUND = 195,142,105
; background #2a1a4a
BACKGROUND = 42,26,74


; generated from https://github.com/clach04/base24_colortool
