; Slugname smyck
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Smyck
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #1b1b1b
DARK_BLACK = 27,27,27

; ANSI Black Bright
; 1;30m
; base03 #838383
BRIGHT_BLACK = 131,131,131

; ANSI Red
; 31m / 41m
; base08 #b74131
DARK_RED = 183,65,49

; ANSI Red Bright
; 1;31m
; base12 #d6837b
BRIGHT_RED = 214,131,123

; ANSI Green
; 32m / 42m
; base0B #7da900
DARK_GREEN = 125,169,0

; ANSI Green Bright
; 1;32m
; base14 #c4f036
BRIGHT_GREEN = 196,240,54

; ANSI Yellow
; 33m / 43m
; base0A #8dcff0
DARK_YELLOW = 141,207,240

; ANSI Yellow Bright
; 1;33m
; base13 #fee14d
BRIGHT_YELLOW = 254,225,77

; ANSI Blue
; 34m / 44m
; base0D #62a3c4
DARK_BLUE = 98,163,196

; ANSI Blue Bright
; 1;34m
; base16 #8dcff0
BRIGHT_BLUE = 141,207,240

; ANSI Magenta
; 35m / 45m
; base0E #b98acc
DARK_MAGENTA = 185,138,204

; ANSI Magenta Bright
; 1;35m
; base17 #f799ff
BRIGHT_MAGENTA = 247,153,255

; ANSI Cyan
; 36m / 46m
; base0C #207383
DARK_CYAN = 32,115,131

; ANSI Cyan Bright
; 1;36m
; base15 #69d9cf
BRIGHT_CYAN = 105,217,207

; ANSI White
; 37m / 47m
; base06 #a0a0a0
DARK_WHITE = 160,160,160

; ANSI White Bright
; 1;37m
; base07 #f7f7f7
BRIGHT_WHITE = 247,247,247

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #969696
FOREGROUND = 150,150,150
; background #1b1b1b
BACKGROUND = 27,27,27


; generated from https://github.com/clach04/base24_colortool
