; Slugname ayu-light
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Ayu Light
author  =  Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)

[table]

; ANSI Black
; 30m / 40m
; base00 #f8f9fa
DARK_BLACK = 248,249,250

; ANSI Black Bright
; 1;30m
; base03 #a0a6ac
BRIGHT_BLACK = 160,166,172

; ANSI Red
; 31m / 41m
; base08 #f07171
DARK_RED = 240,113,113

; ANSI Red Bright
; 1;31m
; base12 #ff7383
BRIGHT_RED = 255,115,131

; ANSI Green
; 32m / 42m
; base0B #6cbf49
DARK_GREEN = 108,191,73

; ANSI Green Bright
; 1;32m
; base14 #86b300
BRIGHT_GREEN = 134,179,0

; ANSI Yellow
; 33m / 43m
; base0A #f2ae49
DARK_YELLOW = 242,174,73

; ANSI Yellow Bright
; 1;33m
; base13 #ffaa33
BRIGHT_YELLOW = 255,170,51

; ANSI Blue
; 34m / 44m
; base0D #399ee6
DARK_BLUE = 57,158,230

; ANSI Blue Bright
; 1;34m
; base16 #478acc
BRIGHT_BLUE = 71,138,204

; ANSI Magenta
; 35m / 45m
; base0E #a37acc
DARK_MAGENTA = 163,122,204

; ANSI Magenta Bright
; 1;35m
; base17 #b595d6
BRIGHT_MAGENTA = 181,149,214

; ANSI Cyan
; 36m / 46m
; base0C #4cbf99
DARK_CYAN = 76,191,153

; ANSI Cyan Bright
; 1;36m
; base15 #55b4d4
BRIGHT_CYAN = 85,180,212

; ANSI White
; 37m / 47m
; base06 #4e5257
DARK_WHITE = 78,82,87

; ANSI White Bright
; 1;37m
; base07 #404447
BRIGHT_WHITE = 64,68,71

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #5c6166
FOREGROUND = 92,97,102
; background #f8f9fa
BACKGROUND = 248,249,250


; generated from https://github.com/clach04/base24_colortool
