; Slugname highway
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Highway
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #212224
DARK_BLACK = 33,34,36

; ANSI Black Bright
; 1;30m
; base03 #807672
BRIGHT_BLACK = 128,118,114

; ANSI Red
; 31m / 41m
; base08 #cf0d17
DARK_RED = 207,13,23

; ANSI Red Bright
; 1;31m
; base12 #ef7d17
BRIGHT_RED = 239,125,23

; ANSI Green
; 32m / 42m
; base0B #128033
DARK_GREEN = 18,128,51

; ANSI Green Bright
; 1;32m
; base14 #b1d130
BRIGHT_GREEN = 177,209,48

; ANSI Yellow
; 33m / 43m
; base0A #4fc2fd
DARK_YELLOW = 79,194,253

; ANSI Yellow Bright
; 1;33m
; base13 #fff11f
BRIGHT_YELLOW = 255,241,31

; ANSI Blue
; 34m / 44m
; base0D #006ab3
DARK_BLUE = 0,106,179

; ANSI Blue Bright
; 1;34m
; base16 #4fc2fd
BRIGHT_BLUE = 79,194,253

; ANSI Magenta
; 35m / 45m
; base0E #6a2674
DARK_MAGENTA = 106,38,116

; ANSI Magenta Bright
; 1;35m
; base17 #de0070
BRIGHT_MAGENTA = 222,0,112

; ANSI Cyan
; 36m / 46m
; base0C #384563
DARK_CYAN = 56,69,99

; ANSI Cyan Bright
; 1;36m
; base15 #5c4f49
BRIGHT_CYAN = 92,79,73

; ANSI White
; 37m / 47m
; base06 #ededed
DARK_WHITE = 237,237,237

; ANSI White Bright
; 1;37m
; base07 #fefffe
BRIGHT_WHITE = 254,255,254

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #c8c5c4
FOREGROUND = 200,197,196
; background #212224
BACKGROUND = 33,34,36


; generated from https://github.com/clach04/base24_colortool
