; Slugname chalk
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Chalk
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #151515
DARK_BLACK = 21,21,21

; ANSI Black Bright
; 1;30m
; base03 #505050
BRIGHT_BLACK = 80,80,80

; ANSI Red
; 31m / 41m
; base08 #fa859c
DARK_RED = 250,133,156

; ANSI Red Bright
; 1;31m
; base12 #fb9fb1
BRIGHT_RED = 251,159,177

; ANSI Green
; 32m / 42m
; base0B #a1bb54
DARK_GREEN = 161,187,84

; ANSI Green Bright
; 1;32m
; base14 #acc267
BRIGHT_GREEN = 172,194,103

; ANSI Yellow
; 33m / 43m
; base0A #ddb26f
DARK_YELLOW = 221,178,111

; ANSI Yellow Bright
; 1;33m
; base13 #eda987
BRIGHT_YELLOW = 237,169,135

; ANSI Blue
; 34m / 44m
; base0D #5ab9ed
DARK_BLUE = 90,185,237

; ANSI Blue Bright
; 1;34m
; base16 #6fc2ef
BRIGHT_BLUE = 111,194,239

; ANSI Magenta
; 35m / 45m
; base0E #db8fea
DARK_MAGENTA = 219,143,234

; ANSI Magenta Bright
; 1;35m
; base17 #e1a3ee
BRIGHT_MAGENTA = 225,163,238

; ANSI Cyan
; 36m / 46m
; base0C #10bcad
DARK_CYAN = 16,188,173

; ANSI Cyan Bright
; 1;36m
; base15 #12cfc0
BRIGHT_CYAN = 18,207,192

; ANSI White
; 37m / 47m
; base06 #e0e0e0
DARK_WHITE = 224,224,224

; ANSI White Bright
; 1;37m
; base07 #f5f5f5
BRIGHT_WHITE = 245,245,245

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #d0d0d0
FOREGROUND = 208,208,208
; background #151515
BACKGROUND = 21,21,21


; generated from https://github.com/clach04/base24_colortool
