; Slugname seafoam-pastel
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Seafoam Pastel
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #243434
DARK_BLACK = 36,52,52

; ANSI Black Bright
; 1;30m
; base03 #9f9f9f
BRIGHT_BLACK = 159,159,159

; ANSI Red
; 31m / 41m
; base08 #825d4d
DARK_RED = 130,93,77

; ANSI Red Bright
; 1;31m
; base12 #cf9379
BRIGHT_RED = 207,147,121

; ANSI Green
; 32m / 42m
; base0B #718c61
DARK_GREEN = 113,140,97

; ANSI Green Bright
; 1;32m
; base14 #98d9aa
BRIGHT_GREEN = 152,217,170

; ANSI Yellow
; 33m / 43m
; base0A #79c3cf
DARK_YELLOW = 121,195,207

; ANSI Yellow Bright
; 1;33m
; base13 #fae79d
BRIGHT_YELLOW = 250,231,157

; ANSI Blue
; 34m / 44m
; base0D #4d7b82
DARK_BLUE = 77,123,130

; ANSI Blue Bright
; 1;34m
; base16 #79c3cf
BRIGHT_BLUE = 121,195,207

; ANSI Magenta
; 35m / 45m
; base0E #8a7167
DARK_MAGENTA = 138,113,103

; ANSI Magenta Bright
; 1;35m
; base17 #d6b2a1
BRIGHT_MAGENTA = 214,178,161

; ANSI Cyan
; 36m / 46m
; base0C #719393
DARK_CYAN = 113,147,147

; ANSI Cyan Bright
; 1;36m
; base15 #ade0e0
BRIGHT_CYAN = 173,224,224

; ANSI White
; 37m / 47m
; base06 #e0e0e0
DARK_WHITE = 224,224,224

; ANSI White Bright
; 1;37m
; base07 #e0e0e0
BRIGHT_WHITE = 224,224,224

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #cacaca
FOREGROUND = 202,202,202
; background #243434
BACKGROUND = 36,52,52


; generated from https://github.com/clach04/base24_colortool
