; Slugname red-planet
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Red Planet
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #222222
DARK_BLACK = 34,34,34

; ANSI Black Bright
; 1;30m
; base03 #7b7773
BRIGHT_BLACK = 123,119,115

; ANSI Red
; 31m / 41m
; base08 #8c3432
DARK_RED = 140,52,50

; ANSI Red Bright
; 1;31m
; base12 #b55242
BRIGHT_RED = 181,82,66

; ANSI Green
; 32m / 42m
; base0B #728271
DARK_GREEN = 114,130,113

; ANSI Green Bright
; 1;32m
; base14 #869985
BRIGHT_GREEN = 134,153,133

; ANSI Yellow
; 33m / 43m
; base0A #60827e
DARK_YELLOW = 96,130,126

; ANSI Yellow Bright
; 1;33m
; base13 #ebeb91
BRIGHT_YELLOW = 235,235,145

; ANSI Blue
; 34m / 44m
; base0D #69809e
DARK_BLUE = 105,128,158

; ANSI Blue Bright
; 1;34m
; base16 #60827e
BRIGHT_BLUE = 96,130,126

; ANSI Magenta
; 35m / 45m
; base0E #896492
DARK_MAGENTA = 137,100,146

; ANSI Magenta Bright
; 1;35m
; base17 #de4873
BRIGHT_MAGENTA = 222,72,115

; ANSI Cyan
; 36m / 46m
; base0C #5b8390
DARK_CYAN = 91,131,144

; ANSI Cyan Bright
; 1;36m
; base15 #38add8
BRIGHT_CYAN = 56,173,216

; ANSI White
; 37m / 47m
; base06 #b9aa99
DARK_WHITE = 185,170,153

; ANSI White Bright
; 1;37m
; base07 #d6bfb8
BRIGHT_WHITE = 214,191,184

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #a4998c
FOREGROUND = 164,153,140
; background #222222
BACKGROUND = 34,34,34


; generated from https://github.com/clach04/base24_colortool
