; Slugname earthsong
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Earthsong
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #282420
DARK_BLACK = 40,36,32

; ANSI Black Bright
; 1;30m
; base03 #857769
BRIGHT_BLACK = 133,119,105

; ANSI Red
; 31m / 41m
; base08 #c84134
DARK_RED = 200,65,52

; ANSI Red Bright
; 1;31m
; base12 #ff6459
BRIGHT_RED = 255,100,89

; ANSI Green
; 32m / 42m
; base0B #84c44b
DARK_GREEN = 132,196,75

; ANSI Green Bright
; 1;32m
; base14 #97e035
BRIGHT_GREEN = 151,224,53

; ANSI Yellow
; 33m / 43m
; base0A #5ed9ff
DARK_YELLOW = 94,217,255

; ANSI Yellow Bright
; 1;33m
; base13 #dfd561
BRIGHT_YELLOW = 223,213,97

; ANSI Blue
; 34m / 44m
; base0D #1397b9
DARK_BLUE = 19,151,185

; ANSI Blue Bright
; 1;34m
; base16 #5ed9ff
BRIGHT_BLUE = 94,217,255

; ANSI Magenta
; 35m / 45m
; base0E #d0623c
DARK_MAGENTA = 208,98,60

; ANSI Magenta Bright
; 1;35m
; base17 #ff9168
BRIGHT_MAGENTA = 255,145,104

; ANSI Cyan
; 36m / 46m
; base0C #4f9452
DARK_CYAN = 79,148,82

; ANSI Cyan Bright
; 1;36m
; base15 #83ef88
BRIGHT_CYAN = 131,239,136

; ANSI White
; 37m / 47m
; base06 #e5c5a9
DARK_WHITE = 229,197,169

; ANSI White Bright
; 1;37m
; base07 #f6f6ec
BRIGHT_WHITE = 246,246,236

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #c5ab93
FOREGROUND = 197,171,147
; background #282420
BACKGROUND = 40,36,32


; generated from https://github.com/clach04/base24_colortool
