; Slugname hopscotch
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Hopscotch
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #322931
DARK_BLACK = 50,41,49

; ANSI Black Bright
; 1;30m
; base03 #898388
BRIGHT_BLACK = 137,131,136

; ANSI Red
; 31m / 41m
; base08 #dd464c
DARK_RED = 221,70,76

; ANSI Red Bright
; 1;31m
; base12 #fd8b19
BRIGHT_RED = 253,139,25

; ANSI Green
; 32m / 42m
; base0B #8fc13e
DARK_GREEN = 143,193,62

; ANSI Green Bright
; 1;32m
; base14 #433b42
BRIGHT_GREEN = 67,59,66

; ANSI Yellow
; 33m / 43m
; base0A #989498
DARK_YELLOW = 152,148,152

; ANSI Yellow Bright
; 1;33m
; base13 #5c545b
BRIGHT_YELLOW = 92,84,91

; ANSI Blue
; 34m / 44m
; base0D #1290bf
DARK_BLUE = 18,144,191

; ANSI Blue Bright
; 1;34m
; base16 #989498
BRIGHT_BLUE = 152,148,152

; ANSI Magenta
; 35m / 45m
; base0E #c85e7c
DARK_MAGENTA = 200,94,124

; ANSI Magenta Bright
; 1;35m
; base17 #d5d3d5
BRIGHT_MAGENTA = 213,211,213

; ANSI Cyan
; 36m / 46m
; base0C #149b93
DARK_CYAN = 20,155,147

; ANSI Cyan Bright
; 1;36m
; base15 #b33508
BRIGHT_CYAN = 179,53,8

; ANSI White
; 37m / 47m
; base06 #b9b5b8
DARK_WHITE = 185,181,184

; ANSI White Bright
; 1;37m
; base07 #ffffff
BRIGHT_WHITE = 255,255,255

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #a9a4a8
FOREGROUND = 169,164,168
; background #322931
BACKGROUND = 50,41,49


; generated from https://github.com/clach04/base24_colortool
