; Slugname mission-brogue
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Mission Brogue
author  =  Thomas Leon Highbaugh

[table]

; ANSI Black
; 30m / 40m
; base00 #283139
DARK_BLACK = 40,49,57

; ANSI Black Bright
; 1;30m
; base03 #60778a
BRIGHT_BLACK = 96,119,138

; ANSI Red
; 31m / 41m
; base08 #efa9a9
DARK_RED = 239,169,169

; ANSI Red Bright
; 1;31m
; base12 #f6bfbf
BRIGHT_RED = 246,191,191

; ANSI Green
; 32m / 42m
; base0B #8cd4b0
DARK_GREEN = 140,212,176

; ANSI Green Bright
; 1;32m
; base14 #b5e090
BRIGHT_GREEN = 181,224,144

; ANSI Yellow
; 33m / 43m
; base0A #e0b88a
DARK_YELLOW = 224,184,138

; ANSI Yellow Bright
; 1;33m
; base13 #fff0b2
BRIGHT_YELLOW = 255,240,178

; ANSI Blue
; 34m / 44m
; base0D #a2c5fd
DARK_BLUE = 162,197,253

; ANSI Blue Bright
; 1;34m
; base16 #c3d9fd
BRIGHT_BLUE = 195,217,253

; ANSI Magenta
; 35m / 45m
; base0E #ccb7db
DARK_MAGENTA = 204,183,219

; ANSI Magenta Bright
; 1;35m
; base17 #e3c3e6
BRIGHT_MAGENTA = 227,195,230

; ANSI Cyan
; 36m / 46m
; base0C #93dfec
DARK_CYAN = 147,223,236

; ANSI Cyan Bright
; 1;36m
; base15 #b2f0fd
BRIGHT_CYAN = 178,240,253

; ANSI White
; 37m / 47m
; base06 #abb9c4
DARK_WHITE = 171,185,196

; ANSI White Bright
; 1;37m
; base07 #e7ebee
BRIGHT_WHITE = 231,235,238

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #93a5b4
FOREGROUND = 147,165,180
; background #283139
BACKGROUND = 40,49,57


; generated from https://github.com/clach04/base24_colortool
