; Slugname mona-lisa
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Mona Lisa
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #110b0d
DARK_BLACK = 17,11,13

; ANSI Black Bright
; 1;30m
; base03 #a26734
BRIGHT_BLACK = 162,103,52

; ANSI Red
; 31m / 41m
; base08 #9b281b
DARK_RED = 155,40,27

; ANSI Red Bright
; 1;31m
; base12 #ff4230
BRIGHT_RED = 255,66,48

; ANSI Green
; 32m / 42m
; base0B #626132
DARK_GREEN = 98,97,50

; ANSI Green Bright
; 1;32m
; base14 #b3b163
BRIGHT_GREEN = 179,177,99

; ANSI Yellow
; 33m / 43m
; base0A #9eb2b3
DARK_YELLOW = 158,178,179

; ANSI Yellow Bright
; 1;33m
; base13 #ff9565
BRIGHT_YELLOW = 255,149,101

; ANSI Blue
; 34m / 44m
; base0D #515b5c
DARK_BLUE = 81,91,92

; ANSI Blue Bright
; 1;34m
; base16 #9eb2b3
BRIGHT_BLUE = 158,178,179

; ANSI Magenta
; 35m / 45m
; base0E #9b1d29
DARK_MAGENTA = 155,29,41

; ANSI Magenta Bright
; 1;35m
; base17 #ff5b6a
BRIGHT_MAGENTA = 255,91,106

; ANSI Cyan
; 36m / 46m
; base0C #588056
DARK_CYAN = 88,128,86

; ANSI Cyan Bright
; 1;36m
; base15 #89cc8e
BRIGHT_CYAN = 137,204,142

; ANSI White
; 37m / 47m
; base06 #f6d75c
DARK_WHITE = 246,215,92

; ANSI White Bright
; 1;37m
; base07 #ffe597
BRIGHT_WHITE = 255,229,151

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #dab14e
FOREGROUND = 218,177,78
; background #110b0d
BACKGROUND = 17,11,13


; generated from https://github.com/clach04/base24_colortool
