; Slugname twilight
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Twilight
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #141414
DARK_BLACK = 20,20,20

; ANSI Black Bright
; 1;30m
; base03 #5c5c51
BRIGHT_BLACK = 92,92,81

; ANSI Red
; 31m / 41m
; base08 #c06c43
DARK_RED = 192,108,67

; ANSI Red Bright
; 1;31m
; base12 #dd7c4c
BRIGHT_RED = 221,124,76

; ANSI Green
; 32m / 42m
; base0B #afb979
DARK_GREEN = 175,185,121

; ANSI Green Bright
; 1;32m
; base14 #cbd88c
BRIGHT_GREEN = 203,216,140

; ANSI Yellow
; 33m / 43m
; base0A #5a5d61
DARK_YELLOW = 90,93,97

; ANSI Yellow Bright
; 1;33m
; base13 #e1c47d
BRIGHT_YELLOW = 225,196,125

; ANSI Blue
; 34m / 44m
; base0D #444649
DARK_BLUE = 68,70,73

; ANSI Blue Bright
; 1;34m
; base16 #5a5d61
BRIGHT_BLUE = 90,93,97

; ANSI Magenta
; 35m / 45m
; base0E #b4be7b
DARK_MAGENTA = 180,190,123

; ANSI Magenta Bright
; 1;35m
; base17 #d0db8e
BRIGHT_MAGENTA = 208,219,142

; ANSI Cyan
; 36m / 46m
; base0C #778284
DARK_CYAN = 119,130,132

; ANSI Cyan Bright
; 1;36m
; base15 #8a989a
BRIGHT_CYAN = 138,152,154

; ANSI White
; 37m / 47m
; base06 #feffd3
DARK_WHITE = 254,255,211

; ANSI White Bright
; 1;37m
; base07 #feffd3
BRIGHT_WHITE = 254,255,211

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #c8c8a7
FOREGROUND = 200,200,167
; background #141414
BACKGROUND = 20,20,20


; generated from https://github.com/clach04/base24_colortool
