; Slugname catppuccin-mocha
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Catppuccin Mocha
author  =  https://github.com/catppuccin/catppuccin

[table]

; ANSI Black
; 30m / 40m
; base00 #1e1e2e
DARK_BLACK = 30,30,46

; ANSI Black Bright
; 1;30m
; base03 #45475a
BRIGHT_BLACK = 69,71,90

; ANSI Red
; 31m / 41m
; base08 #f38ba8
DARK_RED = 243,139,168

; ANSI Red Bright
; 1;31m
; base12 #eba0ac
BRIGHT_RED = 235,160,172

; ANSI Green
; 32m / 42m
; base0B #a6e3a1
DARK_GREEN = 166,227,161

; ANSI Green Bright
; 1;32m
; base14 #a6e3a1
BRIGHT_GREEN = 166,227,161

; ANSI Yellow
; 33m / 43m
; base0A #f9e2af
DARK_YELLOW = 249,226,175

; ANSI Yellow Bright
; 1;33m
; base13 #f5e0dc
BRIGHT_YELLOW = 245,224,220

; ANSI Blue
; 34m / 44m
; base0D #89b4fa
DARK_BLUE = 137,180,250

; ANSI Blue Bright
; 1;34m
; base16 #74c7ec
BRIGHT_BLUE = 116,199,236

; ANSI Magenta
; 35m / 45m
; base0E #cba6f7
DARK_MAGENTA = 203,166,247

; ANSI Magenta Bright
; 1;35m
; base17 #f5c2e7
BRIGHT_MAGENTA = 245,194,231

; ANSI Cyan
; 36m / 46m
; base0C #94e2d5
DARK_CYAN = 148,226,213

; ANSI Cyan Bright
; 1;36m
; base15 #89dceb
BRIGHT_CYAN = 137,220,235

; ANSI White
; 37m / 47m
; base06 #f5e0dc
DARK_WHITE = 245,224,220

; ANSI White Bright
; 1;37m
; base07 #b4befe
BRIGHT_WHITE = 180,190,254

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #cdd6f4
FOREGROUND = 205,214,244
; background #1e1e2e
BACKGROUND = 30,30,46


; generated from https://github.com/clach04/base24_colortool
