; Slugname grape
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Grape
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #161423
DARK_BLACK = 22,20,35

; ANSI Black Bright
; 1;30m
; base03 #696377
BRIGHT_BLACK = 105,99,119

; ANSI Red
; 31m / 41m
; base08 #ec2160
DARK_RED = 236,33,96

; ANSI Red Bright
; 1;31m
; base12 #f0719a
BRIGHT_RED = 240,113,154

; ANSI Green
; 32m / 42m
; base0B #1fa91b
DARK_GREEN = 31,169,27

; ANSI Green Bright
; 1;32m
; base14 #52a95d
BRIGHT_GREEN = 82,169,93

; ANSI Yellow
; 33m / 43m
; base0A #a9bbeb
DARK_YELLOW = 169,187,235

; ANSI Yellow Bright
; 1;33m
; base13 #b2dc87
BRIGHT_YELLOW = 178,220,135

; ANSI Blue
; 34m / 44m
; base0D #487cf4
DARK_BLUE = 72,124,244

; ANSI Blue Bright
; 1;34m
; base16 #a9bbeb
BRIGHT_BLUE = 169,187,235

; ANSI Magenta
; 35m / 45m
; base0E #8c35c8
DARK_MAGENTA = 140,53,200

; ANSI Magenta Bright
; 1;35m
; base17 #ac81c1
BRIGHT_MAGENTA = 172,129,193

; ANSI Cyan
; 36m / 46m
; base0C #3added
DARK_CYAN = 58,221,237

; ANSI Cyan Bright
; 1;36m
; base15 #9ce3ea
BRIGHT_CYAN = 156,227,234

; ANSI White
; 37m / 47m
; base06 #9e9ea0
DARK_WHITE = 158,158,160

; ANSI White Bright
; 1;37m
; base07 #a188f7
BRIGHT_WHITE = 161,136,247

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #8c8a92
FOREGROUND = 140,138,146
; background #161423
BACKGROUND = 22,20,35


; generated from https://github.com/clach04/base24_colortool
