; Slugname builtin-tango-light
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Builtin Tango Light
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #ffffff
DARK_BLACK = 255,255,255

; ANSI Black Bright
; 1;30m
; base03 #737772
BRIGHT_BLACK = 115,119,114

; ANSI Red
; 31m / 41m
; base08 #cc0000
DARK_RED = 204,0,0

; ANSI Red Bright
; 1;31m
; base12 #ef2828
BRIGHT_RED = 239,40,40

; ANSI Green
; 32m / 42m
; base0B #4e9a05
DARK_GREEN = 78,154,5

; ANSI Green Bright
; 1;32m
; base14 #8ae234
BRIGHT_GREEN = 138,226,52

; ANSI Yellow
; 33m / 43m
; base0A #719ecf
DARK_YELLOW = 113,158,207

; ANSI Yellow Bright
; 1;33m
; base13 #fce94e
BRIGHT_YELLOW = 252,233,78

; ANSI Blue
; 34m / 44m
; base0D #3464a4
DARK_BLUE = 52,100,164

; ANSI Blue Bright
; 1;34m
; base16 #719ecf
BRIGHT_BLUE = 113,158,207

; ANSI Magenta
; 35m / 45m
; base0E #74507a
DARK_MAGENTA = 116,80,122

; ANSI Magenta Bright
; 1;35m
; base17 #ad7ea7
BRIGHT_MAGENTA = 173,126,167

; ANSI Cyan
; 36m / 46m
; base0C #05989a
DARK_CYAN = 5,152,154

; ANSI Cyan Bright
; 1;36m
; base15 #34e2e2
BRIGHT_CYAN = 52,226,226

; ANSI White
; 37m / 47m
; base06 #d3d7cf
DARK_WHITE = 211,215,207

; ANSI White Bright
; 1;37m
; base07 #ededec
BRIGHT_WHITE = 237,237,236

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #b3b7b0
FOREGROUND = 179,183,176
; background #ffffff
BACKGROUND = 255,255,255


; generated from https://github.com/clach04/base24_colortool
