; Slugname piatto-light
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Piatto Light
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #ffffff
DARK_BLACK = 255,255,255

; ANSI Black Bright
; 1;30m
; base03 #c1c1c1
BRIGHT_BLACK = 193,193,193

; ANSI Red
; 31m / 41m
; base08 #b23771
DARK_RED = 178,55,113

; ANSI Red Bright
; 1;31m
; base12 #db3365
BRIGHT_RED = 219,51,101

; ANSI Green
; 32m / 42m
; base0B #66781e
DARK_GREEN = 102,120,30

; ANSI Green Bright
; 1;32m
; base14 #829429
BRIGHT_GREEN = 130,148,41

; ANSI Yellow
; 33m / 43m
; base0A #cda434
DARK_YELLOW = 205,164,52

; ANSI Yellow Bright
; 1;33m
; base13 #cd6f34
BRIGHT_YELLOW = 205,111,52

; ANSI Blue
; 34m / 44m
; base0D #3c5ea8
DARK_BLUE = 60,94,168

; ANSI Blue Bright
; 1;34m
; base16 #3c5ea8
BRIGHT_BLUE = 60,94,168

; ANSI Magenta
; 35m / 45m
; base0E #a454b2
DARK_MAGENTA = 164,84,178

; ANSI Magenta Bright
; 1;35m
; base17 #a454b2
BRIGHT_MAGENTA = 164,84,178

; ANSI Cyan
; 36m / 46m
; base0C #1e7878
DARK_CYAN = 30,120,120

; ANSI Cyan Bright
; 1;36m
; base15 #175e5e
BRIGHT_CYAN = 23,94,94

; ANSI White
; 37m / 47m
; base06 #414141
DARK_WHITE = 65,65,65

; ANSI White Bright
; 1;37m
; base07 #212121
BRIGHT_WHITE = 33,33,33

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #515151
FOREGROUND = 81,81,81
; background #ffffff
BACKGROUND = 255,255,255


; generated from https://github.com/clach04/base24_colortool
