; Slugname pnevma
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Pnevma
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #1c1c1c
DARK_BLACK = 28,28,28

; ANSI Black Bright
; 1;30m
; base03 #6b6a67
BRIGHT_BLACK = 107,106,103

; ANSI Red
; 31m / 41m
; base08 #a36666
DARK_RED = 163,102,102

; ANSI Red Bright
; 1;31m
; base12 #d78787
BRIGHT_RED = 215,135,135

; ANSI Green
; 32m / 42m
; base0B #90a57d
DARK_GREEN = 144,165,125

; ANSI Green Bright
; 1;32m
; base14 #afbea2
BRIGHT_GREEN = 175,190,162

; ANSI Yellow
; 33m / 43m
; base0A #a1bdce
DARK_YELLOW = 161,189,206

; ANSI Yellow Bright
; 1;33m
; base13 #e4c9af
BRIGHT_YELLOW = 228,201,175

; ANSI Blue
; 34m / 44m
; base0D #7fa5bd
DARK_BLUE = 127,165,189

; ANSI Blue Bright
; 1;34m
; base16 #a1bdce
BRIGHT_BLUE = 161,189,206

; ANSI Magenta
; 35m / 45m
; base0E #c79ec4
DARK_MAGENTA = 199,158,196

; ANSI Magenta Bright
; 1;35m
; base17 #d7beda
BRIGHT_MAGENTA = 215,190,218

; ANSI Cyan
; 36m / 46m
; base0C #8adbb4
DARK_CYAN = 138,219,180

; ANSI Cyan Bright
; 1;36m
; base15 #b1e7dd
BRIGHT_CYAN = 177,231,221

; ANSI White
; 37m / 47m
; base06 #d0d0d0
DARK_WHITE = 208,208,208

; ANSI White Bright
; 1;37m
; base07 #efefef
BRIGHT_WHITE = 239,239,239

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #aeaead
FOREGROUND = 174,174,173
; background #1c1c1c
BACKGROUND = 28,28,28


; generated from https://github.com/clach04/base24_colortool
