; Slugname elemental
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Elemental
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #21211c
DARK_BLACK = 33,33,28

; ANSI Black Bright
; 1;30m
; base03 #5f5d50
BRIGHT_BLACK = 95,93,80

; ANSI Red
; 31m / 41m
; base08 #97280f
DARK_RED = 151,40,15

; ANSI Red Bright
; 1;31m
; base12 #df502a
BRIGHT_RED = 223,80,42

; ANSI Green
; 32m / 42m
; base0B #479942
DARK_GREEN = 71,153,66

; ANSI Green Bright
; 1;32m
; base14 #60e06f
BRIGHT_GREEN = 96,224,111

; ANSI Yellow
; 33m / 43m
; base0A #78d8d8
DARK_YELLOW = 120,216,216

; ANSI Yellow Bright
; 1;33m
; base13 #d69827
BRIGHT_YELLOW = 214,152,39

; ANSI Blue
; 34m / 44m
; base0D #497f7d
DARK_BLUE = 73,127,125

; ANSI Blue Bright
; 1;34m
; base16 #78d8d8
BRIGHT_BLUE = 120,216,216

; ANSI Magenta
; 35m / 45m
; base0E #7e4e2e
DARK_MAGENTA = 126,78,46

; ANSI Magenta Bright
; 1;35m
; base17 #cd7c53
BRIGHT_MAGENTA = 205,124,83

; ANSI Cyan
; 36m / 46m
; base0C #387f58
DARK_CYAN = 56,127,88

; ANSI Cyan Bright
; 1;36m
; base15 #58d598
BRIGHT_CYAN = 88,213,152

; ANSI White
; 37m / 47m
; base06 #807974
DARK_WHITE = 128,121,116

; ANSI White Bright
; 1;37m
; base07 #fff1e8
BRIGHT_WHITE = 255,241,232

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #756f68
FOREGROUND = 117,111,104
; background #21211c
BACKGROUND = 33,33,28


; generated from https://github.com/clach04/base24_colortool
