; Slugname sleepy-hollow
; for use with colortool / Color Tool April 2019
; from https://github.com/microsoft/terminal/releases/tag/1904.29002
[info]
name  =  Sleepy Hollow
author  =  FredHappyface (https://github.com/fredHappyface)

[table]

; ANSI Black
; 30m / 40m
; base00 #121213
DARK_BLACK = 18,18,19

; ANSI Black Bright
; 1;30m
; base03 #665e6c
BRIGHT_BLACK = 102,94,108

; ANSI Red
; 31m / 41m
; base08 #b93934
DARK_RED = 185,57,52

; ANSI Red Bright
; 1;31m
; base12 #d9443e
BRIGHT_RED = 217,68,62

; ANSI Green
; 32m / 42m
; base0B #90773e
DARK_GREEN = 144,119,62

; ANSI Green Bright
; 1;32m
; base14 #d6b04e
BRIGHT_GREEN = 214,176,78

; ANSI Yellow
; 33m / 43m
; base0A #8085ef
DARK_YELLOW = 128,133,239

; ANSI Yellow Bright
; 1;33m
; base13 #f66713
BRIGHT_YELLOW = 246,103,19

; ANSI Blue
; 34m / 44m
; base0D #5e62b4
DARK_BLUE = 94,98,180

; ANSI Blue Bright
; 1;34m
; base16 #8085ef
BRIGHT_BLUE = 128,133,239

; ANSI Magenta
; 35m / 45m
; base0E #a07c7b
DARK_MAGENTA = 160,124,123

; ANSI Magenta Bright
; 1;35m
; base17 #e1c2ba
BRIGHT_MAGENTA = 225,194,186

; ANSI Cyan
; 36m / 46m
; base0C #8eaea9
DARK_CYAN = 142,174,169

; ANSI Cyan Bright
; 1;36m
; base15 #a4dbe7
BRIGHT_CYAN = 164,219,231

; ANSI White
; 37m / 47m
; base06 #af9a91
DARK_WHITE = 175,154,145

; ANSI White Bright
; 1;37m
; base07 #d1c7a9
BRIGHT_WHITE = 209,199,169

; https://github.com/microsoft/terminal/blob/7a83c0f1679ccac4c3f24f031bf403bd000ab320/src/tools/ColorTool/schemes/campbell.ini#L19-L25
; unclear if can use RGB, this is a test
[screen]
;FOREGROUND = DARK_WHITE
;BACKGROUND = DARK_BLACK
; foreground #968684
FOREGROUND = 150,134,132
; background #121213
BACKGROUND = 18,18,19


; generated from https://github.com/clach04/base24_colortool
